### ISSUE TITLE
no connect after update to 0.0.69

### ISSUE THREAD

**Issue by IngoEF** [fl4p/batmon-ha#137]
Describe the issue here.
since the update from 0.0.68 batmon doesn't display any values from daly bms which works fine and I can connect via smartphone.
How can I revert to the former version?
```
BEGIN 
  File "/usr/lib/python3.11/site-packages/bleak/backends/scanner.py", line 234, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/lib/python3.11/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 156, in start
    assert_reply(reply)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 37, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 80, in __call__
    return await self.sample()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 102, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 293, in __aenter__
    await self.connect()
  File "/app/bmslib/models/daly.py", line 94, in connect
    await self._connect_with_scanner(timeout=timeout)
  File "/app/bmslib/bt.py", line 210, in _connect_with_scanner
    await scanner.start()
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 156, in start
    assert_reply(reply)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
22:11:42 INFO [sampling] connecting bms DalyBt(96:69:08:01:06:A7,Batterie-1)
22:11:42 INFO [daly] normal connect failed ([org.bluez.Error.InProgress] Operation already in progress), connecting with scanner
22:11:42 ERROR [sampling] Batterie-1 error: [org.bluez.Error.InProgress] Operation already in progress
22:11:42 INFO [sampling] Bleak version 0.13.1a1
22:11:42 ERROR [main] Error (num 172, max 200) reading BMS: [org.bluez.Error.InProgress] Operation already in progress
22:11:42 ERROR [main] Stack: Traceback (most recent call last):
  File "/app/bmslib/models/daly.py", line 91, in connect
    await super().connect(timeout=timeout)
  File "/app/bmslib/bt.py", line 189, in connect
    await self._connect_client(timeout=timeout)
  File "/app/bmslib/bt.py", line 153, in _connect_client
    await asyncio.wait_for(self.client.connect(timeout=timeout), timeout=timeout + 1)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bleak/backends/scanner.py", line 205, in find_device_by_address
    return await cls.find_device_by_filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bleak/backends/scanner.py", line 234, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/lib/python3.11/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 156, in start
    assert_reply(reply)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 37, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 80, in __call__
    return await self.sample()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 102, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 293, in __aenter__
    await self.connect()
  File "/app/bmslib/models/daly.py", line 94, in connect
    await self._connect_with_scanner(timeout=timeout)
  File "/app/bmslib/bt.py", line 210, in _connect_with_scanner
    await scanner.start()
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 156, in start
    assert_reply(reply)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
22:11:47 INFO [main] exit signal handler... (15, <frame at 0x7f92ab0f40, file '/usr/lib/python3.11/selectors.py', line 468, code select>), {}, shutdown already False
22:11:47 INFO [main] fetch_loop <bmslib.sampling.BmsSampler object at 0x7f92aa53d0> ends
22:11:47 WARNING [main] Done= {<Task finished name='Task-5' coro=<fetch_loop() done, defined at /app/main.py:33> result=None>}, Pending=set()
22:11:47 WARNING [main] Task <Task finished name='Task-5' coro=<fetch_loop() done, defined at /app/main.py:33> result=None> is done=True
22:11:47 INFO [main] All fetch loops ended. shutdown is already 1
22:11:47 INFO [main] Disconnecting DalyBt(96:69:08:01:06:A7,Batterie-1)
22:11:47 INFO [main] exit signal handler... (), {}, shutdown already True
END
```

**Comment by IngoEF** [comment]
forget this issue.
after powercycling raspi the connection to daly bms came up normally.
