### ISSUE TITLE
victron Operation failed with ATT error: 0x0e (Unlikely Error)

### ISSUE THREAD

**Issue by fl4p** [fl4p/batmon-ha#156]
```
5:45:56 INFO [sampling] Bleak version 0.20.2
15:45:56 ERROR [main] Error (num 6, max 200) reading BMS: 
15:45:56 ERROR [main] Stack: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 390, in call
    await future
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 39, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 90, in __call__
    return await self.sample()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 112, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 325, in __aenter__
    await self.connect()
  File "/app/bmslib/models/victron.py", line 80, in connect
    await super().connect(timeout=timeout)
  File "/app/bmslib/bt.py", line 221, in connect
    await self._connect_client(timeout=timeout)
  File "/app/bmslib/bt.py", line 176, in _connect_client
    await asyncio.wait_for(self.client.connect(timeout=timeout), timeout=timeout + 1)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 141, in connect
    async with async_timeout(timeout):
  File "/usr/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
15:45:56 INFO [sampling] connecting bms SmartShuntBt(E0:E5:16:A0:5A:C8,inverter_in)
15:46:00 ERROR [base_events] Task exception was never retrieved
future: <Task finished name='Task-5161' coro=<SmartShuntBt._keep_alive_loop() done, defined at /app/bmslib/models/victron.py:58> exception=BleakDBusError('org.bluez.Error.Failed', 'Operation failed with ATT error: 0x0e')>
Traceback (most recent call last):
  File "/app/bmslib/models/victron.py", line 63, in _keep_alive_loop
    await self.client.write_gatt_char('6597ffff-4bda-4c1e-af4b-551c4cf74769', data, response=False)
  File "/usr/lib/python3.11/site-packages/bleak/__init__.py", line 659, in write_gatt_char
    await self._backend.write_gatt_char(char_specifier, data, response)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 905, in write_gatt_char
    assert_reply(reply)
  File "/usr/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)

```

**Comment by fl4p** [comment]
This error sometimes appears but doesn’t stay for a long time.
RPI 4, bleak 0.20
