### ISSUE TITLE
First HA setup of the add-on 

### ISSUE THREAD

**Issue by djismgaming** [fl4p/batmon-ha#21]
Hi, so much thanks for this effort!
This is my first installation of this addon.

I do get an error on the latest Home Assistant 2022.9.7 when trying to connect to a SmartShunt via bluetooth.

```
INFO     [victron.py:63] Connecting DA:88:D3:60:A0:50 to pair
ERROR    [main.py:205] 1 exceptions occurred fetching BMSs
ERROR    [main.py:83] Error (num 2) reading BMS: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
ERROR    [main.py:84] Stack: Traceback (most recent call last):
  File "/app/main.py", line 79, in fetch_loop
    await fn()
  File "/app/main.py", line 206, in fn
    raise exceptions[0]
  File "/app/main.py", line 201, in fn
    await t
  File "/app/main.py", line 118, in _fetch_victron
    result = await victron.fetch_device(dev['address'], psk=dev.get('pin'))
  File "/app/victron.py", line 64, in fetch_device
    async with BleakClient(address, handle_pairing=bool(psk)) as client:
  File "/usr/lib/python3.10/site-packages/bleak/backends/client.py", line 97, in __aenter__
    await self.connect()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 205, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 234, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 145, in start
    assert_reply(reply)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
```

I've tried rebuilding the add-on with the bluetooth integration setup and without it setup (thought it was not taking the bluetooth USB device). Tried downgrading to 2022.6.7 (the last before the python breaking changes in 2022.7) but nothing changed so far.

This is my configuration for the addon:

```
devices:
  - address: DA:88:D3:60:A0:50
    type: victron
    alias: LiFePo4
    pin: "PINHERE"
mqtt_user: user
mqtt_password: password
mqtt_broker: core-mosquitto
concurrent_sampling: false
keep_alive: false
verbose_log: true
sample_period: 30
invert_current: true
```

**Comment by djismgaming** [comment]
I lowered the `sample_period` and found the addon actually stops after some time:

```
INFO     [victron.py:63] Connecting DA:88:D3:60:A0:50 to pair
ERROR    [main.py:205] 1 exceptions occurred fetching BMSs
ERROR    [main.py:83] Error (num 41) reading BMS: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
ERROR    [main.py:84] Stack: Traceback (most recent call last):
  File "/app/main.py", line 79, in fetch_loop
    await fn()
  File "/app/main.py", line 206, in fn
    raise exceptions[0]
  File "/app/main.py", line 201, in fn
    await t
  File "/app/main.py", line 118, in _fetch_victron
    result = await victron.fetch_device(dev['address'], psk=dev.get('pin'))
  File "/app/victron.py", line 64, in fetch_device
    async with BleakClient(address, handle_pairing=bool(psk)) as client:
  File "/usr/lib/python3.10/site-packages/bleak/backends/client.py", line 97, in __aenter__
    await self.connect()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 205, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 234, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/lib/python3.10/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 145, in start
    assert_reply(reply)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
WARNING  [main.py:86] too many errors, abort
INFO     [main.py:213] Shutting down ...
INFO     [main.py:227] exit signal handler...
Exception ignored in: <function PairingAgentBlueZDBus.__del__ at 0x7f4a898cd120>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/agent.py", line 64, in __del__
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
  File "/usr/lib/python3.10/asyncio/tasks.py", line 634, in _ensure_future
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
RuntimeError: There is no current event loop in thread 'MainThread'.
sys:1: RuntimeWarning: coroutine 'PairingAgentBlueZDBus.unregister' was never awaited
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by djismgaming** [comment]
Issue fixed after host restart with the USB dongle inserted.
