### ISSUE TITLE
SOK-AA14796 error (#2): <class 'TimeoutError'>

### ISSUE THREAD

**Issue by goldriver2** [fl4p/batmon-ha#222]
I installed the 1.78 version of Batmon, starting the plugin, I can see that it detects my SOK battery i have looking at the log file:
09:48:29 INFO [bt] BT Discovery:
09:48:34 INFO [bt] BT F0:82:88:7C:75:9D             MPPT Av 250/70
09:48:34 INFO [bt] BT 90:CE:B8:3B:84:B1          90-CE-B8-3B-84-B1
09:48:34 INFO [bt] BT 4F:8F:8F:BC:6F:18          4F-8F-8F-BC-6F-18
09:48:34 INFO [bt] BT C0:87:86:18:7A:4E           DV3300S-4.0-1A4E
09:48:34 INFO [bt] BT 01:B6:EC:DA:8F:8B                SOK-AA14794
09:48:34 INFO [bt] BT 01:B6:EC:D9:0A:79                SOK-AA14796
09:48:34 INFO [bt] BT 08:66:98:CC:6D:0A          08-66-98-CC-6D-0A
09:48:34 INFO [bt] BT EA:D4:D7:81:1C:29 SmartBatterySense HQ2102QI2VR
09:48:34 INFO [bt] BT CC:7B:6D:1B:30:62       MPPT 100/20 portable
09:48:34 INFO [bt] BT 08:3A:8D:89:47:0E        EasyTouch 352007359
09:48:34 INFO [bt] BT 0F:7B:1C:B1:4E:CF          0F-7B-1C-B1-4E-CF
09:48:34 INFO [bt] BT C4:93:10:DE:EC:DD       SmartBMV HQ2010NK334
09:48:34 INFO [bt] BT D5:D5:84:4C:71:8D            MPPT Arr 150/85
09:48:34 INFO [bt] BT F4:9F:53:50:E8:00                      N03UM
09:48:34 INFO [bt] BT E0:7F:7D:87:90:E3          E0-7F-7D-87-90-E3
09:48:34 INFO [bt] BT DC:0D:30:46:0A:6A                     maison
09:48:34 INFO [bt] BT 7D:61:1B:E3:6D:28          7D-61-1B-E3-6D-28

using SOK BMS
bt_power_cycle ENABLE
keep_alive ENABLE
install_newer_bleak TOGGLE ON

Paste log output between BEGIN and END:
BEGIN 

But it seems like there is a problem when it tries to connect to them:

09:50:09 INFO [sampling] connecting bms SokBt(01:B6:EC:DA:8F:8B,SOK-AA14794)
09:50:09 INFO [bt] connecting SOK-AA14794 (01:B6:EC:DA:8F:8B) adapter=default timeout=20
09:50:29 ERROR [sampling] SOK-AA14794 error (#3): <class 'TimeoutError'>
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 390, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bmslib/sampling.py", line 155, in __call__
    s = await self._sample_inner()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 227, in _sample_inner
    async with bms:
  File "/app/bmslib/bt.py", line 345, in __aenter__
    await self.connect()
  File "/app/bmslib/models/sok.py", line 106, in connect
    await super().connect(**kwargs)
  File "/app/bmslib/bt.py", line 237, in connect
    await self._connect_client(timeout=timeout)
  File "/app/bmslib/bt.py", line 186, in _connect_client
    await asyncio.wait_for(self.client.connect(timeout=timeout), timeout=timeout + 1)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 141, in connect
    async with async_timeout(timeout):
  File "/usr/lib/python3.11/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
END
```

**Comment by fl4p** [comment]
Fixed in **2.09**: the `sok` type now routes through the aiobmsble `abc_bms` decoder, which correctly parses the frame format current SOK/ABC firmware sends. The native driver waited for a frame terminator this firmware never sends, causing the `timeout waiting for XX` hang.

On 2.09 keep `type: sok` — no config change needed. To try it sooner, set `type: abc`. The old driver stays available as `type: sok_legacy`.

Closing as fixed; please reopen if 2.09 still times out for you.
