### ISSUE TITLE
Algorithms not working for Jikong BMS

### ISSUE THREAD

**Issue by alexeyklots** [fl4p/batmon-ha#234]
I tried to use Algorithms feature with JIKONG BMS But got an error

* Include exact BMS model name - JK_B1A8S10P 

```
Paste log output between BEGIN and END:
15:00:24 INFO [algorithm] Max Soc reached, stop charging
15:00:24 ERROR [sampling] jk2 error (#1): BatterySwitches.__init__() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "/app/bmslib/sampling.py", line 155, in __call__
    s = await self._sample_inner()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 283, in _sample_inner
    BatterySwitches(**sample.switches), res)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BatterySwitches.__init__() got an unexpected keyword argument 'balance'
```

Potentially related to the added Balance switch feature to Jikong bms

Thanks for such a great solution!

**Comment by fl4p** [comment]
Confirmed bug, now fixed. The algorithm log line splatted the BMS switch dict into `BatterySwitches(charge, discharge)`, but a JK also reports `balance`/`float_charge`, so it threw `unexpected keyword argument 'balance'` the moment the algo acted (your "Max Soc reached, stop charging"). The switch-apply loop underneath had the same fault (KeyError on `balance`, plus it hardcoded the `charge` switch). Both fixed on master — ships in the next release.
