### ISSUE TITLE
Error loggin

### ISSUE THREAD

**Issue by Didierp31** [fl4p/batmon-ha#247]
Bms daly (dont know model)

Thanks

ERROR [main] Main loop exception: 'DalyBt' object has no attribute 'logger'

Logs : 

00:31:41 INFO [main] Bleak version 0.13.1a1, BtBackend version bluez-v5.76
00:31:42 ERROR [main] Main loop exception: 'DalyBt' object has no attribute 'logger'
00:31:42 ERROR [main] Stack: Traceback (most recent call last):
  File "/app/main.py", line 359, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/main.py", line 147, in main
    bms = construct_bms(dev, verbose_log, devices)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/models/__init__.py", line 63, in construct_bms
    return bms_class(addr,
           ^^^^^^^^^^^^^^^
  File "/app/bmslib/models/daly.py", line 65, in __init__
    self.logger.warning('JBD usually does not use a pairing PIN')
    ^^^^^^^^^^^
AttributeError: 'DalyBt' object has no attribute 'logger'

**Comment by fl4p** [comment]
Remove the `pin` field from the Daly BMS device entry.
