### ISSUE TITLE
Victron shunt

### ISSUE THREAD

**Issue by Homekit-Josh** [fl4p/batmon-ha#255]
File "/app/venv/lib/python3.12/site-packages/bleak/backends/scanner.py", line 205, in find_device_by_address
    return await cls.find_device_by_filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/bleak/backends/scanner.py", line 234, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/app/venv/lib/python3.12/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/app/venv/lib/python3.12/site-packages/bleak/backends/bluezdbus/scanner.py", line 115, in start
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/dbus_next/aio/message_bus.py", line 305, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 36, in fetch_loop
    if await fn():
       ^^^^^^^^^^
  File "/app/main.py", line 319, in fn
cannot connect to Victron shunt.

    raise exceptions[0]
  File "/app/main.py", line 314, in fn
    await t()
  File "/app/bmslib/sampling.py", line 155, in __call__
    s = await self._sample_inner()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/sampling.py", line 227, in _sample_inner
    async with bms:
  File "/app/bmslib/bt.py", line 345, in __aenter__
    await self.connect()
  File "/app/bmslib/models/victron.py", line 84, in connect
    await super().connect(timeout=timeout)
  File "/app/bmslib/bt.py", line 237, in connect
    await self._connect_client(timeout=timeout)
  File "/app/bmslib/bt.py", line 186, in _connect_client
    await asyncio.wait_for(self.client.connect(timeout=timeout), timeout=timeout + 1)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by fl4p** [comment]
The connect timed out during the scan, so the shunt was never seen by the adapter. For a SmartShunt: update its firmware, enable GATT in VictronConnect, set the pairing `pin:` in the device entry (see README), and keep the phone app disconnected. Closing as stale; open a new issue with a `verbose_log` if a current version still cannot connect.
