### ISSUE TITLE
Error in mqtt auto configuration

### ISSUE THREAD

**Issue by Niceman35** [fl4p/batmon-ha#36]
From HA logs:

2022-11-23 23:18:59.551 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'unique_id': 'battery1__switch_charge', 'name': 'battery1 charge switch', 'device_class': 'outlet', 'json_attributes_topic': 'battery1/charge', 'expire_after': 40, 'device': {'identifiers': ['battery1'], 'name': 'battery1'}, 'state_topic': 'battery1/switch/charge', 'command_topic': 'homeassistant/switch/battery1/charge/set', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 327, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected BinarySensorDeviceClass or one of 'battery', 'battery_charging', 'carbon_monoxide', 'cold', 'connectivity', 'door', 'garage_door', 'gas', 'heat', 'light', 'lock', 'moisture', 'motion', 'moving', 'occupancy', 'opening', 'plug', 'power', 'presence', 'problem', 'running', 'safety', 'smoke', 'sound', 'tamper', 'update', 'vibration', 'window' for dictionary value @ data['device_class']

'device_class': 'outlet' is not in BinarySensorDeviceClass. Change to 'plug' maybe.

**Comment by fl4p** [comment]
thanks, fix with next release
