### ISSUE TITLE
not work bms jkbms

### ISSUE THREAD

**Issue by amgstone** [fl4p/batmon-ha#53]
`devices:
  - address: C8:47:8C:E8:FF:73
    type: jk
    alias: Irenahouse_48
    pin: "123456"
mqtt_user: roman
mqtt_password: "513024400"
mqtt_broker: core-mosquitto
concurrent_sampling: true
keep_alive: true
verbose_log: false
sample_period: 10
publish_period: 2
invert_current: true
watchdog: true
expire_values_after: 20
debug: true`

`ERROR    [sampling.py:125] Irenahouse_48 error: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
ERROR    [main.py:85] Error (num 3) reading BMS: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/app/bmslib/jikong.py", line 112, in connect
    await super().connect(timeout=4)
  File "/app/bmslib/bt.py", line 26, in connect
    await self.client.connect(timeout=timeout)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 198, in connect
    raise BleakError(
bleak.exc.BleakError: Device with address C8:47:8C:E8:FF:73 was not found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 47, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 65, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 113, in __aenter__
    await self.connect()
  File "/app/bmslib/jikong.py", line 115, in connect
    await self._connect_with_scanner(timeout=timeout)
  File "/app/bmslib/bt.py", line 47, in _connect_with_scanner
    raise Exception('Device %s not discovered (%s)' % (self.client.address, discovered))
Exception: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
INFO     [sampling.py:61] connecting bms JKBt(C8:47:8C:E8:FF:73)
INFO     [jikong.py:114] normal connect failed, connecting with scanner
ERROR    [sampling.py:125] Irenahouse_48 error: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
ERROR    [main.py:85] Error (num 4) reading BMS: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/app/bmslib/jikong.py", line 112, in connect
    await super().connect(timeout=4)
  File "/app/bmslib/bt.py", line 26, in connect
    await self.client.connect(timeout=timeout)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 198, in connect
    raise BleakError(
bleak.exc.BleakError: Device with address C8:47:8C:E8:FF:73 was not found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 47, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 65, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 113, in __aenter__
    await self.connect()
  File "/app/bmslib/jikong.py", line 115, in connect
    await self._connect_with_scanner(timeout=timeout)
  File "/app/bmslib/bt.py", line 47, in _connect_with_scanner
    raise Exception('Device %s not discovered (%s)' % (self.client.address, discovered))
Exception: Device C8:47:8C:E8:FF:73 not discovered ({'B8:BC:5B:A9:98:AB'})
INFO     [sampling.py:61] connecting bms JKBt(C8:47:8C:E8:FF:73)
INFO     [jikong.py:114] normal connect failed, connecting with scanner
ERROR    [main.py:120] MQTT never published a message after 120s, exit
ERROR    [sampling.py:125] Irenahouse_48 error: Device C8:47:8C:E8:FF:73 not discovered (set())
ERROR    [main.py:85] Error (num 5) reading BMS: Device C8:47:8C:E8:FF:73 not discovered (set())
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/app/bmslib/jikong.py", line 112, in connect
    await super().connect(timeout=4)
  File "/app/bmslib/bt.py", line 26, in connect
    await self.client.connect(timeout=timeout)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 198, in connect
    raise BleakError(
bleak.exc.BleakError: Device with address C8:47:8C:E8:FF:73 was not found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/bmslib/sampling.py", line 47, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 65, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 113, in __aenter__
    await self.connect()
  File "/app/bmslib/jikong.py", line 115, in connect
    await self._connect_with_scanner(timeout=timeout)
  File "/app/bmslib/bt.py", line 47, in _connect_with_scanner
    raise Exception('Device %s not discovered (%s)' % (self.client.address, discovered))
Exception: Device C8:47:8C:E8:FF:73 not discovered (set())
INFO     [main.py:282] Shutting down ...
INFO     [main.py:289] Disconnecting JKBt(C8:47:8C:E8:FF:73)
INFO     [main.py:298] exit signal handler...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

![1](https://user-images.githubusercontent.com/63303107/216935340-9379c653-44fb-4df2-8dcb-3d2f2e9a28dc.jpg)
![Screenshot_2023-02-06-11-39-39-069_com jktech bms](https://user-images.githubusercontent.com/63303107/216938012-04c9aa3f-1d3c-4d5f-bb4a-18403cd05dec.jpg)

**Comment by fl4p** [comment]
Make sure the BMS is in range and close the iOS App
