### ISSUE TITLE
JBD BMS: "Operation failed with ATT error: 0x0e (Connection Rejected Due To Security Reasons)"

### ISSUE THREAD

**Issue by MariusHerget** [fl4p/batmon-ha#75]
Hey, since today the connection to my integrated jbd BMS does not work anymore:

```
21:51:39 INFO [sampling] connecting bms JbdBt(XX:XX:XX:XX:XX:XX)
21:51:40 ERROR [client] Pairing /org/bluez/hci0/dev_A4_C1_38_DE_A8_13 with hci0 failed (org.bluez.Error.AuthenticationFailed)
21:51:40 ERROR [bt] Pairing failed!
21:51:40 ERROR [sampling] camper_belluna_01 error: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Connection Rejected Due To Security Reasons)
21:51:40 ERROR [main] 1 exceptions occurred fetching BMSs
21:51:40 ERROR [main] Error (num 41, max 200) reading BMS: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Connection Rejected Due To Security Reasons)
21:51:40 ERROR [main] Stack: Traceback (most recent call last):
  File "/app/main.py", line 45, in fetch_loop
    await fn()
  File "/app/main.py", line 234, in fn
    raise exceptions[0]
  File "/app/main.py", line 229, in fn
    await t
  File "/app/bmslib/sampling.py", line 50, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 68, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 164, in __aenter__
    await self.connect()
  File "/app/bmslib/jbd.py", line 58, in connect
    await self.client.start_notify(self.UUID_RX, self._notification_handler)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 1077, in start_notify
    assert_reply(reply)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Connection Rejected Due To Security Reasons)
21:51:40 WARNING [bt] BMS JbdBt(XX:XX:XX:XX:XX:XX) disconnected!
21:51:41 INFO [sampling] connecting bms JbdBt(XX:XX:XX:XX:XX:XX)
21:51:41 ERROR [client] Pairing /org/bluez/hci0/dev_A4_C1_38_DE_A8_13 with hci0 failed (org.bluez.Error.AuthenticationFailed)
21:51:41 ERROR [bt] Pairing failed!
21:51:41 INFO [sampling] connected bms JbdBt(XX:XX:XX:XX:XX:XX)!
21:51:41 ERROR [sampling] camper_belluna_01 error: Not connected
21:51:41 ERROR [main] 1 exceptions occurred fetching BMSs
21:51:41 ERROR [main] Error (num 42, max 200) reading BMS: Not connected
21:51:41 ERROR [main] Stack: Traceback (most recent call last):
  File "/app/main.py", line 45, in fetch_loop
    await fn()
  File "/app/main.py", line 234, in fn
    raise exceptions[0]
  File "/app/main.py", line 229, in fn
    await t
  File "/app/bmslib/sampling.py", line 50, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 72, in sample
    sample = await bms.fetch()
  File "/app/bmslib/jbd.py", line 73, in fetch
    buf = await self._q(cmd=0x03)
  File "/app/bmslib/jbd.py", line 66, in _q
    await self.client.write_gatt_char(self.UUID_TX, data=_jbd_command(cmd))
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 896, in write_gatt_char
    raise BleakError("Not connected")
bleak.exc.BleakError: Not connected
21:51:41 WARNING [bt] BMS JbdBt(XX:XX:XX:XX:XX:XX) disconnected!
21:51:42 INFO [sampling] connecting bms JbdBt(XX:XX:XX:XX:XX:XX)
```

Is this related to the latest update or is it only my setup?

**Comment by MariusHerget** [comment]
Nevermind. My BMS just decided to remove the pin on itself.
